### PR TITLE
Python 3 compatibility and various improvements

### PR DESCRIPTION
**Pull request by hansenmc**
Tests were also added and the code has been refactored to process the Manage API JSON responses a little more generically.
 
These changes address the following issues:
- #14 Plugin not working with Python v3.5
- #25 Invalid URL in Setup.py file
- #27 ERROR 'int' object has no attribute '__getitem__' with MarkLogic 9.0-8.2
- #33 Connection error causes system.exit

Also incorporates changes for the following PRs.
- #31 resolve pylint warnings
- #32 adjust copyright to 2019 
- #33 expand the list of exceptions to handle, making the plugin less likely to exit
- #34 fix marklogic-community links

### CODE REVIEW

**Comment by xquery** [comment]
This is a big set of commits, though from what I scanned everything looks good.

Happy to see your use of pylint - FWIW  I use black and pylint as 'make format' and 'make lint' in most of my python projects (as well as generate docs with pdoc3 and static types via annotations mypy style) - something I find very useful. Originally I also wanted to add a travis build (to run tests) and mock out marklogic server calls  to make the tests standalone but never had time to revisit.

You've taken my crappy prototype code and made something entirely respectable/useful - I hope you do not consider it a burden that I now think you own this codebase. 

Let me know if I can help with anything or if you would like me to review in the future.

**Comment by xquery** [comment]
please merge

also added you as admin of this github project
